Repository LostArtefacts/TR2X, pull requests merged in 2024-09, with the labels that each got.

#169 game: check if the item is still used
  CHANGELOG.md
  src/game/game.c
Labels: OG bug, Priority: high

#192 creature: fix killing skidoo riders via cheat
  src/game/creature.c
  src/game/lara/lara_cheat.c
Labels: TR2X bug, Priority: high

#202 lara-cheat: fix killing certain enemies
  src/game/lara/lara_cheat.c
Labels: TR2X bug, Priority: high

#203 lara-cheat: fix fly cheat and harpoon
  src/game/gun/gun.c
Labels: TR2X bug, Priority: high

#206 inv/backpack: fix regression in Inv_AddItem
  src/game/inventory/backpack.c
  src/game/objects/vars.c
Labels: TR2X bug, Priority: high

#216 lara_cheat: free hands after teleporting
  src/game/lara/lara_cheat.c
Labels: OG bug, Unreleased, Priority: medium

#215 overlay: fix regression in pickup display
  src/game/overlay.c
  src/game/overlay.h
Labels: TR2X bug, Priority: high, Unreleased

#220 console_cmd: avoid teleporting to carried items
  src/game/console_cmd.c
Labels: TR2X bug, Unreleased, Priority: medium

#218 lara_cheat: fix gun status and drawing
  src/game/lara/lara_cheat.c
Labels: TR2X bug, Unreleased, Priority: medium

#212 text: do not nuke all textstrings on level load
  src/decomp/decomp.c
  src/decomp/stats.c
  src/game/game.c
  src/game/inventory/common.c
  src/game/overlay.c
  src/game/overlay.h
  src/inject_exec.c
Labels: TR2X bug, Unreleased, Priority: medium

#223 lara_cheat: amend teleporting approach
  src/game/lara/lara_cheat.c
Labels: TR2X bug, Unreleased, Priority: medium

#224 console: use arrow sprite for caret
  CHANGELOG.md
  src/game/console.c
  src/game/text.c
Labels: Enhancement, Priority: medium

#234 input: fix numeric keys interacting with the demos
  CHANGELOG.md
  src/specific/s_input.c
Labels: OG bug, Priority: low

#235 lara/col: fix regression in Lara_TestWaterStepOut
  CHANGELOG.md
  src/game/lara/lara_col.c
Labels: TR2X bug, Priority: high

#236 lara/col: fix regression in Lara_Col_Walk
  src/game/lara/lara_col.c
Labels: TR2X bug, Priority: high, Unreleased

#238 room_draw: check for outside flag when setting room bounds
  CHANGELOG.md
  src/game/room_draw.c
Labels: OG bug, Priority: medium

#276 lara_control: reset rotation when dismounting vehicle
  CHANGELOG.md
  src/game/lara/control.c
Labels: TR2X bug
